### ISSUE TITLE
React-Select component with properties crash Firefox on Windows 10

### ISSUE THREAD

**Issue by devonbalicki** [JedWatson/react-select#1521]
Affects Firefox 51.0.1 on Windows 10 32 and 64 bit

When loading a React-Select component that has properties set causes the browser window to crash.

```
let props = this.props;
        return (
                <ReactSelect {...props} noResultsText={ '' }/>
        );
```

This loads fine:

```
let props = this.props;
        return (
                <ReactSelect/>
        );
```

Crash report: https://crash-stats.mozilla.com/report/index/20c12273-27b2-4e1c-b49f-874492170131

cc @peixian @tab1293

**Comment by amolbarewar** [comment]
the same issue is happening for our team also. We are facing problem on Firefox version 51.0.1 in Windows Operating system only.
We are using below code snippet.
`<Select
              className = "block"
              clearable = {false}
              name = "hours"
              onChange = {e => onStateChange(e.value, 'scheduletime', 0)}
              options = {hoursSelect}
              searchable = {false}
              value = {(scheduleTime || '00:00').split(':')[0]} />`

**Comment by domehead100** [comment]
I have a user who reported a hang on Firefox 50.0.1 today on a page using react-select 1.0.0-rc.3.  She's on Windows 8.1.  That crash report posted earlier seems to indicate that the hang was caused by Shockwave Flash, I'll check with my user tomorrow.  Will try disabling hardware graphics acceleration, removing Shockwave if it's installed.

The same page works fine for me and some other users on the same version of Firefox.  

Must be either a FF bug or due to some extension that the user has installed, right?  My page works fine in Chrome and IE 11 (not as pleasant of an experience in IE 11, but it works).

**Comment by sabapk** [comment]
Resolved this issue.

So our code base, was using <Select> Component syntax with each prop to be on new line like,
```javascript
<Select
 options = {timezones}
 value = {timezone} />
```
So, we changed our code style to write props inline and surprisingly this one change resolved our issue of browser crashing.
`<Select options = {timezones} value = {timezone} />`

**Comment by sabapk** [comment]
Resolved this issue.

So our code base, was using react-select `Select` Component syntax with each prop to be on new line.
So, we changed our code style to write props inline and surprisingly this one change resolved our issue of browser crashing.

`<Select options = {timezones} value = {timezone} />`

**Comment by blackChef** [comment]
Same issue here. Browser freezing seems to be random on our product.

**Comment by peixian** [comment]
@domehead100 It doesn't seem to be an extension, since FF 51.0.1 still crashes in safe mode with it, so I'm inclined to say it's a weird Windows specific FF bug.

**Comment by domehead100** [comment]
Yeah, probably right; I wasn't sure if safe mode disabled all extensions, plugins, etc.

My user today reports that FF updated this morning when she started it, and now everything works without issues.  She's on Windows 8.1.

**Comment by critesjm** [comment]
Same occurs on a completely fresh install of FFox 51.0.1 x32/x64 on Win7.

**Comment by critesjm** [comment]
More info: initial debugging shows (at least in our case) that the component works if you don't pass in searchable={false}

**Comment by critesjm** [comment]
More info: initial debugging shows (at least in our case) that the component works if you don't pass in searchable={false}

**Comment by omgaz** [comment]
I'm not seeing the problem on FF 51.0.1 x32/x64 on Win10. My `accessibility.force_disable` is also set to `0`. Running the latest rc3.

**Comment by sabapk** [comment]
We debugged the problem with the component. It was happening when we were using `searchable` property as `false` with React-Select component. Quite weird, but we added a hack around it and resolved the issue.

**Comment by noveyak** [comment]
We are experiencing this too on FF 51.01 and Win 10 (But not mac). It seems like 1.0.0-beta13 and earlier still seem to work because all the aria props were not introduced in the code yet. The component also seems to render ok if it is !disabled && searchable && autosize because it goes into a separate render branch.

**Comment by critesjm** [comment]
@omgaz if you set that to -1 it'll force the settings on and may help you to see it.

**Comment by ykabisher** [comment]
Also happens on windows 7 64Bit / FF51
http://jedwatson.github.io/react-select/
in the first example, when disabled is checked or search is unchecked, FF crashes

**Comment by mhubenthal** [comment]
It appears that Firefox is getting stuck in some kind of infinite loop due to incorrect use of `aria-owns` attribute. Here's the W3C spec on `aria-owns`:

https://www.w3.org/TR/wai-aria/states_and_properties#aria-owns

In `Select.js`, line 879, when `isOpen` is false, the component assigns `this._instancePrefix + '-value'` to `aria-owns`. That value corresponds to a DOM node which *is* a parent, and thus has a hierarchical relationship, breaking the W3C spec.

**Comment by mhubenthal** [comment]
PR with a fix is out: #1556

**Comment by agirton** [comment]
#1556 was merged. Closing.
