### ISSUE TITLE
Update examples page with code/options used...

### ISSUE THREAD

**Issue by joetidee** [JedWatson/react-select#2041]
Please could you update the examples page with the exact code/options that were used to generate each example:
http://jedwatson.github.io/react-select/

**Comment by JedWatson** [comment]
Fixed by #2051

**Comment by joetidee** [comment]
Still can't see anything on the examples page that shows the code/options used (?)

**Comment by JedWatson** [comment]
It's in the source and will be published with the next version when the examples are published

Preview here: https://deploy-preview-2074--react-select.netlify.com
