### ISSUE TITLE
Enter key does not open menu while focused

### ISSUE THREAD

**Issue by GonchuB** [JedWatson/react-select#3414]
The menu is not opened when ENTER key is pressed and the menu is closed. From the source ([onKeyDown](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L1183)), it looks like the first option should be focused, but nothing happens

### Steps to reproduce
- Go to https://codesandbox.io/s/00oykp18k0
- Click the Select
- Select "Chocolate"
- With focus still on the Select, press Enter key

### Expected result
- Menu gets opened

### Actual result
- Nothing happens

**Comment by gwyneplaine** [comment]
This is definitely not intended, focusOption should not be called on ENTER if the menu is not open.
Fix for this will be released in v2.4.0 as part of https://github.com/JedWatson/react-select/pull/3427.

**Comment by gwyneplaine** [comment]
resolved in v2.4.0 and closed

**Comment by Veena624** [comment]
This is my workaround:

onKeyDown = (event) => {switch (event.key) {
        case 'Enter':
          if (!this.state.isOpen) {
            this.selectRef.setState({
              menuIsOpen: true,
            });
            break;
        }
      }
    };

<Select ref={el => (this.selectRef = el)}  onKeyDown={this.onKeyDown}  />

**Comment by fkrauthan** [comment]
I guess this issue is back? At least for me if a Dropdown is focused (ether through tab or through a form label for connected to the input) the menu does not open when pressing enter.

**Comment by lgoldb** [comment]
Is this issue back? My team is noticing it with react-select 5.2.2. Can we re-open it?

**Comment by Rall3n** [comment]
@lgoldb This was never an issue. `Enter` is not meant to open the dropdown, only to select an option if the dropdown has been opened.

But you can implement this behaviour by yourself using the `onKeyDown` prop (see https://github.com/JedWatson/react-select/issues/3414#issuecomment-590264726 for possible implementation).

**Comment by IanBoyte** [comment]
> @lgoldb This was never an issue. `Enter` is not meant to open the dropdown, only to select an option if the dropdown has been opened.
> 
> But you can implement this behaviour by yourself using the `onKeyDown` prop (see [#3414 (comment)](https://github.com/JedWatson/react-select/issues/3414#issuecomment-590264726) for possible implementation).

For reference, this might need to be reconsidered. Our third party accessibility audit is requesting that the dropdown be expanded on both spacebar and enter pressed on focus.
