### ISSUE TITLE
Multibyte input value such as Japanese remains when using Multi-select text input

### ISSUE THREAD

**Issue by wild-mouse** [JedWatson/react-select#3557]
When I trying multi-select input on https://react-select.com/creatable and inputted value like 'テスト', input raw value remaining(and if not delete raw value and hit enter again, same select value will be added).

**Comment by razh** [comment]
This should be fixed by https://github.com/JedWatson/react-select/pull/3563.

**Comment by gwyneplaine** [comment]
Thanks for raising this issue @wild-mouse , resolved in #3563  which was shipped in 2.4.4, please update to the latest version of react-select

**Comment by yhiguchi-concerto** [comment]
the same problem remains 'Multi-select text input' on Creatable Example Page though as long as - if you have any advise on how to resolve, it would be great!
