### ISSUE TITLE
Deprecated Context and reference.

### ISSUE THREAD

**Issue by mathieutu** [JedWatson/react-select#3703]
Hi, some usage of Select are now deprecated by React.
In addition to https://github.com/JedWatson/react-select/issues/3191 there are also some problem with context:

```
Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in ErrorBoundary
    in Unknown (created by HotExportedComponent)
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent

Please update the following components: MenuPlacer

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

and reference:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of NodeResolver which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by MenuList)
    in MenuList (created by MenuPlacer)
    in ScrollBlock (created by MenuPlacer)
    in NodeResolver (created by ScrollCaptor)
    in ScrollCaptor (created by ScrollCaptorSwitch)
    in ScrollCaptorSwitch (created by MenuPlacer)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by Menu)
    in Menu (created by MenuPlacer)
    in MenuPlacer (created by Select)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by SelectContainer)
    in SelectContainer (created by Select)
    in Select (created by StateManager)
    in StateManager (created by Select)
    ...

Learn more about using refs safely here:
https://fb.me/react-strict-mode-find-node
```

You can see them here:
https://codesandbox.io/embed/react-codesandboxer-example-vhvre

Thanks.
Matt'

**Comment by dpordomingo** [comment]
Legacy context API warning should be partially addressed by https://github.com/JedWatson/react-select/pull/3928

**Comment by bladey** [comment]
Hi all,

As you may be aware, this bug has been reported multiple times as per issue #4094. On behalf of the maintainers I apologise it's taken awhile to get to this.

A new master issue #4094 has since been created to help keep track of this bug going forward.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4094, please let us know and we'll take another look.

Again, thank you.

**Comment by hemant171k** [comment]
where is solution . if not then why its been closed?

**Comment by bladey** [comment]
Hi @hemant171k, it's currently open.

**Comment by hiimagu** [comment]
Im still having this issue. Did you already merge the solution?

**Comment by Methuselah96** [comment]
@hiimagu The solution has been merged, but not released yet.

**Comment by olelivalife** [comment]
> @hiimagu The solution has been merged, but not released yet.

When do you plan to release it?

**Comment by Methuselah96** [comment]
@olelivalife There is no definite release date and it seems unlikely that it will be soon. The last publish was on March 22. @JedWatson and @bladey have mentioned that they're trying to get a publish out "as soon as possible," but I wouldn't count on it happening anytime soon.

**Comment by piaro** [comment]
I hope that this problem is resolved quickly.

**Comment by pdipeshiw** [comment]
When will we get the fixed version of the release?

**Comment by MaximilianLloyd** [comment]
Is there any workaround for this yet?

**Comment by Methuselah96** [comment]
@MaximilianLloyd I've started a fork where this is fixed in [`react-select-oss@3.1.1`](https://github.com/react-select-oss/react-select/releases/tag/react-select-oss%403.1.1).

**Comment by MrDogeBro** [comment]
Has this new version that fixes this issue been released yet? I am currently using 3.1.1 and the error is still occurring there.

**Comment by Methuselah96** [comment]
@MrDogeBro Track https://github.com/JedWatson/react-select/issues/4094 for more info. The plan is to release the fixes for this in a 4.0 release.

**Comment by MrDogeBro** [comment]
@Methuselah96 ok sounds good. Any ideas on when this update should be released?

**Comment by Methuselah96** [comment]
@MrDogeBro It's primarily dependent on Jed's availability. My guess is sometime within 1-2 months.

**Comment by abhimanusharma** [comment]
@Methuselah96 is the fixed yet?

**Comment by Methuselah96** [comment]
@abhimanusharma Yes, it was fixed in [`react-select@4.0.0`](https://github.com/JedWatson/react-select/releases/tag/react-select%404.0.0).

**Comment by cannon303** [comment]
I'm still getting this error. I've tested everything I can think of to make sure I am up to date but the error remains.

**Comment by Methuselah96** [comment]
Can you provide the error message you're getting?

**Comment by cannon303** [comment]
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Transition, TransitionGroup

Learn more about this warning here: https://reactjs.org/link/legacy-context
TransitionGroup@http://localhost:3000/static/js/vendors~main.chunk.js:326866:30
Route@http://localhost:3000/static/js/vendors~main.chunk.js:324374:29
div
div
TransGroup@http://localhost:3000/static/js/main.chunk.js:1662:88
Router@http://localhost:3000/static/js/vendors~main.chunk.js:324005:30
HashRouter@http://localhost:3000/static/js/vendors~main.chunk.js:323573:35

**Comment by cannon303** [comment]
It doesn't work either. No transitions.

**Comment by Methuselah96** [comment]
Just to confirm, have you tried it with v5?

**Comment by cannon303** [comment]
No sorry is this issue thread related specifically to that?

**Comment by Methuselah96** [comment]
Yeah, we focus our efforts on supporting the latest major version (react-select v5 at the moment). I believe the issue has been fixed in react-select v5 and we don't currently have plans to back-port the fix to earlier major versions.
