### ISSUE TITLE
Selected options are not announced as selected if the object reference changed AriaLive

### ISSUE THREAD

**Issue by MoritzKn** [JedWatson/react-select#5424]
See:
https://codesandbox.io/s/react-select-v5-sandbox-forked-gzdeq6?file=/example.js

As far as I can tell this is due to this code:
https://github.com/JedWatson/react-select/blob/da617c51b810c67d809dfde9cb9f3b5815313d91/packages/react-select/src/components/LiveRegion.tsx#L112-L116

In most places, the object relevance is not relevant. Following this pattern, I think this should look like this:
```rsx
    const isSelected = !!(
      focusedOption &&
      selectValue &&
      selectValue.some(option => option.value === focusedOption.value)
    );
```

I'll send a PR.

**Comment by SetupCoding** [comment]
Can we get that fix merged please? :)

**Comment by Watso196** [comment]
We're still seeing this issue with the current version. Is the fix mentioned still available to be merged?

**Comment by bakerj417** [comment]
We are experiencing this issue too. We have a temporary fix in place but would love to see an official fix.
