### ISSUE TITLE
Touch events do not work when `<Select />` is mounted in a shadow root

### ISSUE THREAD

**Issue by mbeckem** [JedWatson/react-select#5824]
Hi,

the current approach to touch event handling does not work well when `<Select />` is used with a shadow root.

### Reproduction

- Open Stackblitz: https://stackblitz.com/edit/stackblitz-starters-pandyv?file=src%2FApp.tsx
- The Select component works well using clicks (the Menu opens when clicking into the input)
- Open your browser's mobile device emulation (or use a touch device) and touch into the input field
- The menu does not open

### Notes

- The menu actually opens internally, but it is hidden immediately because the [`onTouchEnd` event handler](https://github.com/JedWatson/react-select/blob/06e34882638d1526b9f5a1238bb567a3e9460ce5/packages/react-select/src/Select.tsx#L1461) categorizes the touch event as _outside_ the select control (this results in a `blurInput()` call)
- When inside a shadow root, the event handler registered on the document will not observe the original `.target`, but the entire shadow dom. This is obviously not contained in the original node, which causes the behavior in this case.
- A more stable alternative to `.contains(...)` is to use [`event.composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) instead. See also [this blog post](https://lamplightdev.com/blog/2021/04/10/how-to-detect-clicks-outside-of-a-web-component/).

I've had trouble creating a unit test for this bug (I could not get touch events inside shadow DOM to work with jest). I hope that the sample above will be sufficient.
I think a fix would look as simple as replacing `node.contains(event.target)` with `event.composedPath().includes(node)`. I'll gladly create a PR for this.

Kind regards

**Comment by mbeckem** [comment]
Related: PR #5737 attempts to fix this issue, but I think the approach taken is not optimal

**Comment by shotasenga** [comment]
Tho it's hacky, there is a workaround to this. If you cancel the touch events before they reach the `react-select` components, you can enforce it to use the mouse events instead.

```
<div onTouchEndCapture={(e) => e.stopPropagation()}>
  <Select ..../>
</div>
```

**Comment by mbeckem** [comment]
@shotasenga nice idea, i didn't think of that. We fixed that on our side by patching the select component via pnpm:

```diff
diff --git a/dist/Select-49a62830.esm.js b/dist/Select-49a62830.esm.js
index bed08498732b023f350d24a62728371af6a4dace..23a5fd969db4d0190cc4b6f05417c9594ddc2931 100644
--- a/dist/Select-49a62830.esm.js
+++ b/dist/Select-49a62830.esm.js
@@ -1498,7 +1498,7 @@ var Select = /*#__PURE__*/function (_Component) {
       // close the menu if the user taps outside
       // we're checking on event.target here instead of event.currentTarget, because we want to assert information
       // on events on child elements, not the document (which we've attached this handler to).
-      if (_this.controlRef && !_this.controlRef.contains(event.target) && _this.menuListRef && !_this.menuListRef.contains(event.target)) {
+      if (_this.controlRef && !event.composedPath().includes(_this.controlRef) && _this.menuListRef && !event.composedPath().includes(_this.menuListRef)) {
         _this.blurInput();
       }
```

**Comment by srai612** [comment]
> Tho it's hacky, there is a workaround to this. If you cancel the touch events before they reach the `react-select` components, you can enforce it to use the mouse events instead.
> 
> ```
> <div onTouchEndCapture={(e) => e.stopPropagation()}>
>   <Select ..../>
> </div>
> ```
yes its working fine but when i am clicking outside its not getting close

**Comment by JonathanCaspar** [comment]
This issue is still happening, the suggested solution above fixed the issue.
