### ISSUE TITLE
[1.0.0-beta13] Async options with Promises displays [object Promise] as input value

### ISSUE THREAD

**Issue by matejlauko** [JedWatson/react-select#940]
When loading options async with Promises, like in the example `[object Promise]` string is set as input value of Select
```js
const getOptions = (input) => {
  return fetch(`/users/${input}.json`)
    .then((response) => {
      return response.json();
    }).then((json) => {
      return { options: json };
    });
}

<Select.Async
    loadOptions={getOptions}
/>
```

It is because of #907.

`loadOptions` from Async component attaches to `onInputChange` on Select component.
so this
```js
if (this.state.inputValue !== event.target.value && this.props.onInputChange) {
    let nextState = this.props.onInputChange(newInputValue);
    if (nextState != null) {
        newInputValue = '' + nextState;
    }
 }
```
sets newInputValue to return value of loadOptions, which is `[object Promise]`

**Comment by VladimirPal** [comment]
I've got the same error.
https://github.com/VladimirPal/react-select/tree/async_promise_bug - here i've added example with fetch.js

**Comment by matejlauko** [comment]
@VladimirPal thx for the fix

**Comment by JedWatson** [comment]
Fixed by #941, thanks @VladimirPal!

And thanks @matejlauko for the comprehensive report too :)

**Comment by dvreed77** [comment]
I'm running 1.0.0-beta13 and am still experiencing this bug.

**Comment by VladimirPal** [comment]
@dvreed77 Currently this fix only in master branch

**Comment by dvreed77** [comment]
maybe dumb question, but can I force use this branch from npm?

**Comment by VladimirPal** [comment]
Try this:
`"react-select": "git+ssh://git@github.com:JedWatson/react-select.git"`

**Comment by VladimirPal** [comment]
@dvreed77 But it will not help you:( You have to build lib folder manually.
`cd node_modules/react-select`
`npm install && npm build`

**Comment by dvreed77** [comment]
I am not sure what is happening, but I can't npm to install.  NPM just hangs.  Could be an issue with one of the packages?  Here is a snippet

```
npm http request GET https://registry.npmjs.org/xml-name-validator
npm http 200 https://registry.npmjs.org/array-equal
npm http 304 https://registry.npmjs.org/abab
npm http 304 https://registry.npmjs.org/parse5
npm http 304 https://registry.npmjs.org/nwmatcher
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/whatwg-url
npm http 304 https://registry.npmjs.org/xml-name-validator
npm http 304 https://registry.npmjs.org/symbol-tree
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/cssstyle
npm http 200 https://registry.npmjs.org/webidl-conversions
fetchMetadata -> network
```

**Comment by dvreed77** [comment]
@VladimirPal Was battling some corporate proxy stuff there for a second.  I followed all that, but am still getting the [object Promise] in Select.  

Only difference is I used http protocal vs git: `"react-select": "git+https://github.com/JedWatson/react-select.git"`

**Comment by VladimirPal** [comment]
@dvreed77 i've created builded version, try use it:
`"git+https://github.com/VladimirPal/react-select.git"`

**Comment by dvreed77** [comment]
hmm.  Get this:

```
->npm install git+https://github.com/VladimirPal/react-select.git
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git+https://github.com/VladimirPal/react-select.git"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.8
npm ERR! code ENOSELF

npm ERR! Refusing to install react-select as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by dvreed77** [comment]
I get this:

```
 gulp-babel@5.3.0 node_modules/react-select/node_modules/gulp-babel
- babelify@6.4.0 node_modules/react-select/node_modules/babelify
- react-component-gulp-tasks@0.7.7 node_modules/react-select/node_modules/react-component-gulp-tasks
- babel-eslint@4.1.8 node_modules/react-select/node_modules/babel-eslint
- babel@5.8.38 node_modules/react-select/node_modules/babel
- react-select@1.0.0-beta13 node_modules/react-select/node_modules/react-select
orgchart@1.0.0 /Users/dreed/Projects/orgchart
├── react@15.0.2  extraneous
├── react-dom@15.0.2  extraneous
├── react-select@1.0.0-beta13  invalid (git+https://github.com/VladimirPal/react-select.git#acb3a69464dfe66edf00faef2b7fbebac2f9ddb5)
└── reactify@1.1.1  extraneous

npm WARN orgchart@1.0.0 No description
npm WARN orgchart@1.0.0 No repository field.
```
Note the invalid error

**Comment by dvreed77** [comment]
Also am trying it without browserify and including the .js and .css from /dist directory and am still getting same issue

**Comment by dvreed77** [comment]
@VladimirPal 
I'm closer...  I was using this example code, which doesn't seem to work:

```
const getOptions = (input) => {
  return fetch(`/users/${input}.json`)
    .then((response) => {
      return response.json();
    }).then((json) => {
      return { options: json };
    });
}

<Select.Async
    name="form-field-name"
    value="one"
    loadOptions={getOptions}
/>
```

and now am using something like this:

getUsers: function (input, callback) {
            console.log(input);
            fetch(`/users/${input}.json`)
                .then(function(response) {
                    return response.json()
                })
                .then(function(json) {
                    var data = {
                        options: json,
                        complete: false
                    };
                    callback(null, data);
                });

        },

```

This still isn't quite working, but am not getting the [object Promise] in select window.  

The optionRenderer is only firing on first character, even though I can see elements coming back

**Comment by dvreed77** [comment]
ok, even closer:  had to set `filterOption={function(){ return true; }}` to just pass through

**Comment by mattparrilla** [comment]
@JedWatson any time frame on when this might get released? I'm not familiar with the release cadence but would love to use fetch + react-select for async options!
