### ISSUE TITLE
Multi-select scrolls to top after selecting (v.1.0.0)

### ISSUE THREAD

**Issue by steinso** [JedWatson/react-select#977]
Problem: After selecting an option in a multi-select enabled component, the option menu automatically scrolls to the top.

I have debugged this a bit, and it looks like the reason is that on render it wants to focus the selected option, however in multi-select mode, that option is removed from the option menu. This makes it default to the first element in the menu. 

5th line in render function, and this.getFocusableOption.

One way to go about this could be to find the adjacent option in the props.options list, and then find the same option in the _visibleOptions list.

**Comment by prateekjahead** [comment]
Facing the same issue. I think an expected behaviour would be to maintain the scroll position of the menu on selecting an option and just pull up the remaining options in the list.

**Comment by dsoriano** [comment]
+1
If the PR of @steinso is OK, is it possible to merge ?

**Comment by FourwingsY** [comment]
+1

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
+1

**Comment by BossGrand** [comment]
+1

**Comment by swiharta** [comment]
For me, maybe it's been fixed in the meantime, but it's actually scrolling to the last selected option correctly in `multi` mode. 

But, I wish there was at least the option to scroll to the top, whether multi-select or single. I have no interest in retaining the scroll position of the last selected item for my use case, and the best way I have found to eliminate this is to edit the source code, in componentDidUpdate, I just commented out the first `if` statement block...

``` js
		key: 'componentDidUpdate',
		value: function componentDidUpdate(prevProps, prevState) {
			// focus to the selected option
			if (this.menu && this.focused && this.state.isOpen && !this.hasScrolledToOption) {
				var focusedOptionNode = _reactDom2.default.findDOMNode(this.focused);
				var menuNode = _reactDom2.default.findDOMNode(this.menu);
				menuNode.scrollTop = focusedOptionNode.offsetTop;
				this.hasScrolledToOption = true;
			} else if (!this.state.isOpen) {
				this.hasScrolledToOption = false;
			}
```
If there was an option to disable scrolling (and highlighting), the last selected option (which ends up being the next adjacent option in multi mode), it would be great.

**Comment by vitaliikobrin** [comment]
Hi everyone!

I'm still facing the issue with scroll. I'm using V2 of the component and as I see everything has changed. I cannot find the above code anymore. Do somebody deal with it in 2019? Maybe I missed some component option. Or there is another part of code caused the issue.

This is critical for me as I'd like to keep multi-select opened while a user selects options. The idea is to close the dropdown when a user clicks on submit button inside it. But the dropdown scrolls up every time a user selects an option and this makes the idea totally unusable. 

Is it possible to fix the issue on my side?

**Comment by hogiyogi597** [comment]
+1

**Comment by yashug** [comment]
@vitaliikobrin did you found a solution to this? I am also facing the same issue

**Comment by pbeleckis** [comment]
Any news on this issue? Is there a some kind of workaround?

**Comment by Gazpa** [comment]
Experiencing the same issue. In my case I use the multi option and a custom menu selection popup. On the first click anywhere in the popup container it will scroll to top in case the input is not visible in the page.

**Comment by aliazizi** [comment]
+1

**Comment by aliazizi** [comment]
@bladey why not confirmed? this is a huge bug

**Comment by bladey** [comment]
Hi @aliazizi, thanks for your feedback.

Can you please confirm this issue is still affecting `v3` of `react-select`?

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues using `v1` and `v2` of `react-select`.

In the best interest of supporting the broader community we have to direct our efforts towards the current major version `v3` and beyond.

**Comment by alikrodrigues** [comment]
Hi, I'm not the author.. but I can confirm this issue in **3.1.0**.

![Gravação de Tela 2020-06-15 às 11 29 58](https://user-images.githubusercontent.com/29580644/84670240-3d338680-aefc-11ea-9b74-d3e63d79c3ff.gif)

**Comment by bladey** [comment]
Thanks @alikrodrigues, I appreciate the feedback.

**Comment by bladey** [comment]
@alikrodrigues I just tweaked the sandbox example and I'm unable to reproduce the issue, could you let me know what I'm missing from my config (it also works when searching and selecting).

![MLoom5](https://user-images.githubusercontent.com/737821/84717286-c27c7100-afb8-11ea-9fcc-caa91d3dcd82.gif)

https://codesandbox.io/s/react-codesandboxer-example-ewd44

**Comment by alikrodrigues** [comment]
Hi @bladey thanks for answered, When I use a wrapMenuList to show the selected the focus will redirect to MenuList.. 
When I removed and show just the badges the work it's ok.. 
![Gravação-de-Tela-2020-06-16-às-11 39 53](https://user-images.githubusercontent.com/29580644/84790588-e2fff780-afc7-11ea-807e-dd7b8dfe186f.gif)



Here is my Select Component
![image](https://user-images.githubusercontent.com/29580644/84789582-c7482180-afc6-11ea-9743-ab51e9a86676.png)

and here is my MenuList
![image](https://user-images.githubusercontent.com/29580644/84789773-f9f21a00-afc6-11ea-8a60-f27e002403fe.png)

**Comment by aliazizi** [comment]
@bladey I reproduce the problem

You can see it here

https://codesandbox.io/s/react-codesandboxer-example-5xmq0?file=/index.js

**Comment by calvinherd9** [comment]
Running into this issue also, I have a custom Menu Item component and closeMenuOnSelect set to false. Have you found a workaround to this issue or is this just a bug that can't be solved

**Comment by Rall3n** [comment]
@aliazizi Common mistake with Reacts `render` method: You are defining your `MenuList` component inside the `render` method. As this method is called on every change to the components state, the `MenuList` component is also redefined every time, which causes the HTML element to be replaced and the scroll-to-top to happen.

Solution: Move your component outside of the `render` method.

```jsx
const MenuList = () => { /* ... */ };

/* ...*/

render() {
    return <Select components={{ MenuList }} />;
}
```

**Comment by bladey** [comment]
Thanks for the answer @Rall3n!

I can confirm this works, I modified the Codesandbox here - https://codesandbox.io/s/react-codesandboxer-example-4mj9p?file=/index.js

The problem no longer exists for me @aliazizi and @calvinherd9, let me know.

**Comment by aliazizi** [comment]
@Rall3n! thanks, it's working

@bladey  thank you it's working now

**Comment by alikrodrigues** [comment]
Thanks guys, It's working for me too.

**Comment by Texetomg** [comment]
@Rall3n 
I spent 2 days off looking for a solution and trying to fix this bug. how everything turned out to be trite. thanks !

**Comment by tylerlwsmith** [comment]
A note for anyone else who was struggling with this: React Select seems to use object identity matching under the hood to determine which values are selected. That means if you programmatically generate your `{label, value}` object every render, React Select will have trouble keeping track of it.

For example: the following code will cause React Select to jump to the top after every selection, because different objects are passed to React Select every render (even though they have the same values):

```jsx
import React { useEffect, useState, useMemo } from "react";
import Select from "react-select";
import axios from "axios";

function BlogPostSelect() {

  const [posts, setPosts] = useState(null);

  useEffect(function getPosts() {
    axios.get("/api/posts/)
      .then(({data}) => {
        setPosts(data);
      })
  }, []);

  function makeSelectOptions() {
    return posts.map(post => ({ label: post.title, value: post.id }))
  }

  return (
    <Select
      multi={true}
      closeMenuOnSelected={false}
      hideSelectedOptions={false}
      options={makeSelectOptions()}
  )
}
```

On the other hand, if we computed the list once with `useMemo`, the objects would keep their identities, and React Select would maintain its position and not jump to the top after you select an item.

```jsx
import React { useEffect, useState } from "react";
import Select from "react-select";
import axios from "axios";

function BlogPostSelect() {

  const [posts, setPosts] = useState(null);

  useEffect(function getPosts() {
    axios.get("/api/posts/)
      .then(({data}) => {
        setPosts(data);
      })
  }, []);

  // This is now memoized, so objects maintain their identity.
  const selectOptions =  useMemo(() => {
    return posts.map(post => ({ label: post.title, value: post.id }))
  }, [posts])

  return (
    <Select
      multi={true}
      closeMenuOnSelected={false}
      hideSelectedOptions={false}
      options={makeSelectLabels}
  )
}
```

Hopefully this helps someone in the future. I didn't actually run the code above so there may be a couple of typos, but this general concept got this working for me.

**Comment by ektak26** [comment]
In my case, I want to send some callback functions [onChange] and properties in the menu list component
but when I pass them somehow scroll is not working [when the item is selected it scrolls to the top]

I modified the Codesandbox here https://codesandbox.io/s/react-codesandboxer-example-forked-s0320q?file=/index.js

can anyone please help me with this?
thanks

**Comment by tk21** [comment]
@ektak26 

In your example, it looks like you are still returning a new MenuList on every render with how you have `MenuList: (props) => ....`. If you define it without a function that gets called on every render, then it works. Take a look at this fork of your sandbox: https://codesandbox.io/s/react-codesandboxer-example-forked-t1fytw?file=/index.js

The main thing is that I defined `const customComponents = { MenuList: MenuListCustom };` outside of the component (or you can wrap it in a useMemo if you want) and then for your `Select` component I have the prop:

```
<Select
        ... other props
        components={customComponents}
      />
```

**Comment by Rutra-Selvi-Thavamani** [comment]
When I select the options in multi-select Dropdown, the scroller position is going to top instead of staying at the selected position.
![image](https://user-images.githubusercontent.com/119167992/222943584-cbaf2bf2-03a0-41dc-96ab-f2df4b5d19b2.png)


Here is my code:
![image](https://user-images.githubusercontent.com/119167992/222943647-798ff86a-df74-43ec-a708-78a4422c21c6.png)

Please help me out for this issue

**Comment by vijay1479** [comment]
Please use useCallback with MenuList. That will work.
const MenuList = useCallback((props: any) => {
    return (
      <Fragment>
        <components.MenuList {...props}>{props.children}</components.MenuList>
        <div style={{ textAlign: "center" }}>
          <Button
            size="sm"
            type="button"
          >
            Clear
          </Button>
        </div>
      </Fragment>
    );
  }, []);

**Comment by alexalannunes** [comment]
@vijay1479 you saved my life!

**Comment by marcos-smartflow** [comment]
> @ektak26
> 
> In your example, it looks like you are still returning a new MenuList on every render with how you have `MenuList: (props) => ....`. If you define it without a function that gets called on every render, then it works. Take a look at this fork of your sandbox: https://codesandbox.io/s/react-codesandboxer-example-forked-t1fytw?file=/index.js
> 
> The main thing is that I defined `const customComponents = { MenuList: MenuListCustom };` outside of the component (or you can wrap it in a useMemo if you want) and then for your `Select` component I have the prop:
> 
> ```
> <Select
>         ... other props
>         components={customComponents}
>       />
> ```

what if I need to add a button to change the state at the top of the list? still looking for a solution, I have something like that, and it keeps scrolling to the top as soon as I select an option

```
const MenuList = (props: any) => {
    return (
      <components.MenuList {...props}>
        {selectedAccounts.length > 0 ? (
          <button className="btn btn-link" onClick={() => setSelectedAccounts([])}>
            deselect all accounts
          </button>
        ) : (
          <button className="btn btn-link" onClick={() => setSelectedAccounts(accounts)}>
            select all accounts
          </button>
        )}
        {props.children}
      </components.MenuList>
    )
  }
```

**Comment by amishaaggarwal** [comment]
i am using a custom menuList with customFilter placed above the ul and the menu scrolls to top as soon as I select any option in isMulti mode...is there a solution to this problem?
